use crate::detection::print_compiler_info;
use crate::formats::ExecutableFormat;
use colored::Colorize;
use crc32fast;
use goblin::mach::{Mach, SingleArch};
use goblin::Object;
use md5;
use sha2::{Digest, Sha256};
use std::error::Error;
use std::path::Path;
use std::time::{Duration, UNIX_EPOCH};

const BOX_WIDTH: usize = 75;

fn box_line(content: &str) -> String {
    let inner_width = BOX_WIDTH - 4; // tolgo "| " e " |"
    let padded = format!("{:^inner_width$}", content);
    format!("; |{}|", padded)
}

pub fn print_ida_file_header(bytes: &[u8], file: &Path) -> Result<(), Box<dyn Error>> {
    let top = format!("; +{}+", "-".repeat(BOX_WIDTH - 2));
    let bottom = format!("; +{}+", "-".repeat(BOX_WIDTH - 2));

    println!("{}", top.bright_black());
    println!(
        "{}",
        box_line("This file was generated by rustydump").bright_black()
    );
    println!("{}", box_line("Based on iced-x86 + goblin").bright_black());
    println!("{}", bottom.bright_black());
    println!("{}", ";".bright_black());

    let sha256 = {
        let mut h = Sha256::new();
        h.update(bytes);
        let digest = h.finalize();

        digest
            .iter()
            .map(|b| format!("{:02X}", b))
            .collect::<String>()
    };
    let md5 = format!("{:X}", md5::compute(bytes));
    let crc32 = format!("{:08X}", crc32fast::hash(bytes));

    println!(
        "{} {}",
        "; Input SHA256 :".bright_black(),
        sha256.bright_white()
    );
    println!(
        "{} {}",
        "; Input MD5    :".bright_black(),
        md5.bright_white()
    );
    println!(
        "{} {}",
        "; Input CRC32  :".bright_black(),
        crc32.bright_white()
    );
    println!("{}", ";".bright_black());

    println!(
        "{} {}",
        "; File Name   :".bright_black(),
        file.display().to_string().bright_white()
    );

    match Object::parse(bytes)? {
        Object::PE(pe) => {
            let bits = if pe.is_64 { "AMD64" } else { "i386" };
            println!(
                "{} {}",
                "; Format      :".bright_black(),
                format!("Portable executable for {bits} (PE)").bright_white()
            );
            println!(
                "{} {}",
                "; Imagebase   :".bright_black(),
                format!("{:X}", pe.image_base).bright_white()
            );

            // Timestamp dal COFF header
            if let Some(ts) = format_timestamp(pe.header.coff_header.time_date_stamp) {
                println!("{} {}", "; Timestamp   :".bright_black(), ts.bright_white());
            }

            println!("{}", ";".bright_black());

            for (i, section) in pe.sections.iter().enumerate() {
                let name = section.name().unwrap_or("?");
                let vsize = section.virtual_size;
                let vaddr = section.virtual_address;
                let raw_size = section.size_of_raw_data;
                let raw_off = section.pointer_to_raw_data;
                let chars = section.characteristics;

                println!(
                    "{} {}",
                    "; Name       :".bright_black(),
                    name.bright_white()
                );
                println!(
                    "{} {}",
                    ";".bright_black(),
                    format!("Section {}. (virtual address {:08X})", i + 1, vaddr).bright_black()
                );
                println!(
                    "{} {:08X} ({}.)",
                    "; Virtual size                  :".bright_black(),
                    vsize,
                    vsize
                );
                println!(
                    "{} {:08X} ({}.)",
                    "; Section size in file          :".bright_black(),
                    raw_size,
                    raw_size
                );
                println!(
                    "{} {:08X}",
                    "; Offset to raw data for section:".bright_black(),
                    raw_off
                );
                println!(
                    "{} {:08X}: {}",
                    "; Flags".bright_black(),
                    chars,
                    format_pe_section_flags(Some(chars as u64)).bright_white()
                );
                println!("{}", ";".bright_black());
            }

            print_compiler_info(bytes);
        }
        Object::Elf(elf) => {
            let bits = if elf.is_64 { "x86-64" } else { "i386" };
            println!(
                "{} {}",
                "; Format      :".bright_black(),
                format!("ELF {bits}").bright_white()
            );
            println!(
                "{} {}",
                "; Entry point :".bright_black(),
                format!("0x{:016x}", elf.entry).bright_white()
            );
            println!("{}", ";".bright_black());

            for (i, shdr) in elf.section_headers.iter().enumerate() {
                let name = elf.shdr_strtab.get_at(shdr.sh_name).unwrap_or("?");

                println!(
                    "{} {}",
                    ";".bright_black(),
                    format!(
                        "Section {} '{}' (virtual address {:016X})",
                        i + 1,
                        name,
                        shdr.sh_addr
                    )
                    .bright_black()
                );
                println!(
                    "{} {:016X}",
                    "; Offset      :".bright_black(),
                    shdr.sh_offset
                );
                println!("{} {:016X}", "; Size        :".bright_black(), shdr.sh_size);
                println!(
                    "{} {:016X}: {}",
                    "; Flags       :".bright_black(),
                    shdr.sh_flags,
                    format_elf_section_flags(Some(shdr.sh_flags)).bright_white()
                );
                println!("{}", ";".bright_black());
            }

            print_compiler_info(bytes);
        }
        Object::Mach(mach) => {
            println!(
                "{} {}",
                "; Format      :".bright_black(),
                "Mach-O".bright_white()
            );
            println!("{}", ";".bright_black());

            match mach {
                Mach::Binary(macho) => print_macho_sections(&macho),
                Mach::Fat(fat) => {
                    // Fat binary: contiene più architetture (es. x86_64 + arm64)
                    for arch in fat.into_iter() {
                        match arch? {
                            SingleArch::MachO(macho) => {
                                print_macho_sections(&macho);
                            }
                            SingleArch::Archive(_) => {}
                        }
                    }
                }
            }

            print_compiler_info(bytes);
        }
        _ => {}
    }

    println!(
        "{}",
        "; ==========================================================================="
            .bright_black()
    );
    println!("{}", ";".bright_black());

    Ok(())
}

pub fn print_ida_section_header(
    section_name: &str,
    base_addr: u64,
    flags: Option<u64>,
    format: &Option<ExecutableFormat>,
    is_code: bool,
) {
    println!("{}", ";".bright_black());
    println!(
        "{}",
        "; ==========================================================================="
            .bright_black()
    );
    println!("{}", ";".bright_black());

    let seg_type = if is_code { "Pure code" } else { "Mixed" };
    println!(
        "{} {}",
        "; Segment type:".bright_black(),
        seg_type.bright_white()
    );

    let perms = match format {
        Some(ExecutableFormat::Elf) => format_elf_section_flags(flags),
        Some(ExecutableFormat::PE) => format_pe_section_flags(flags),
        Some(ExecutableFormat::MachO) => format_macho_section_flags(flags),
        None => "".to_string(),
    };
    println!(
        "{} {}",
        "; Segment permissions:".bright_black(),
        perms.bright_white()
    );

    println!("{}", ";".bright_black());

    // Per scherzo label segmento stile IDA: "_text  segment para public 'CODE' use64"
    let seg_label = if is_code {
        format!(
            "_{}\t\tsegment para public 'CODE' use64",
            section_name.trim_start_matches('.')
        )
    } else {
        format!(
            "_{}\t\tsegment para public 'DATA' use64",
            section_name.trim_start_matches('.')
        )
    };
    println!("{}", seg_label.bright_yellow());
    println!(
        "{}",
        format!(
            "\t\t\t\tassume cs:_{}",
            section_name.trim_start_matches('.')
        )
        .bright_black()
    );
    println!(
        "{}",
        format!("\t\t\t\t;org {:X}h", base_addr).bright_black()
    );
    println!();
}

fn format_timestamp(ts: u32) -> Option<String> {
    // Converte il timestamp COFF in stringa leggibile
    let d = UNIX_EPOCH + Duration::from_secs(ts as u64);
    let secs = d.duration_since(UNIX_EPOCH).ok()?.as_secs();
    // Formattazione manuale senza dipendenze extra (chrono)
    Some(format!("{:08X} (Unix timestamp: {})", ts, secs))
}

fn format_elf_section_flags(flags: Option<u64>) -> String {
    let mut out = Vec::new();

    let flags = flags.unwrap_or(0);

    const SHF_WRITE: u64 = 0x1;
    const SHF_ALLOC: u64 = 0x2;
    const SHF_EXECINSTR: u64 = 0x4;
    const SHF_MERGE: u64 = 0x10;
    const SHF_STRINGS: u64 = 0x20;
    const SHF_INFO_LINK: u64 = 0x40;
    const SHF_LINK_ORDER: u64 = 0x80;
    const SHF_TLS: u64 = 0x400;

    if flags & SHF_ALLOC != 0 {
        out.push("Allocated");
    }

    if flags & SHF_EXECINSTR != 0 {
        out.push("Executable");
    }

    if flags & SHF_WRITE != 0 {
        out.push("Writable");
    }

    if flags & SHF_MERGE != 0 {
        out.push("Merge");
    }

    if flags & SHF_STRINGS != 0 {
        out.push("Strings");
    }

    if flags & SHF_INFO_LINK != 0 {
        out.push("InfoLink");
    }

    if flags & SHF_LINK_ORDER != 0 {
        out.push("LinkOrder");
    }

    if flags & SHF_TLS != 0 {
        out.push("TLS");
    }

    out.join(" ")
}

fn format_pe_section_flags(chars: Option<u64>) -> String {
    let mut out = Vec::new();

    let chars = chars.unwrap_or(0) as u32;

    const PE_TEXT: u32 = 0x0000_0020;
    const PE_EXECUTABLE: u32 = 0x2000_0000;
    const PE_READABLE: u32 = 0x4000_0000;
    const PE_WRITEABLE: u32 = 0x8000_0000;
    const PE_DATA: u32 = 0x0000_0040;
    const PE_DISCARDABLE: u32 = 0x0200_0000;

    if chars & PE_TEXT != 0 {
        out.push("Text");
    }

    if chars & PE_EXECUTABLE != 0 {
        out.push("Executable");
    }

    if chars & PE_READABLE != 0 {
        out.push("Readable");
    }

    if chars & PE_WRITEABLE != 0 {
        out.push("Writeable");
    }

    if chars & PE_DATA != 0 {
        out.push("Data");
    }

    if chars & PE_DISCARDABLE != 0 {
        out.push("Discardable");
    }

    out.join(" ")
}

fn format_macho_section_flags(flags: Option<u64>) -> String {
    let mut out = Vec::new();

    let flags = flags.unwrap_or(0) as u32;

    const S_ATTR_PURE_INSTRUCTIONS: u32 = 0x8000_0000;
    const S_ATTR_SOME_INSTRUCTIONS: u32 = 0x0000_0400;
    const S_ATTR_EXT_RELOC: u32 = 0x0000_0200;
    const S_ATTR_LOC_RELOC: u32 = 0x0000_0100;

    if flags & S_ATTR_PURE_INSTRUCTIONS != 0 {
        out.push("PureInstructions");
    }

    if flags & S_ATTR_SOME_INSTRUCTIONS != 0 {
        out.push("Instructions");
    }

    if flags & S_ATTR_EXT_RELOC != 0 {
        out.push("ExternalReloc");
    }

    if flags & S_ATTR_LOC_RELOC != 0 {
        out.push("LocalReloc");
    }

    out.join(" ")
}

fn print_macho_sections(macho: &goblin::mach::MachO<'_>) {
    for (seg_idx, segment) in macho.segments.iter().enumerate() {
        println!(
            "{} {}",
            ";".bright_black(),
            format!(
                "Segment {} '{}' (vmaddr {:016X})",
                seg_idx + 1,
                segment.name().unwrap_or("?"),
                segment.vmaddr
            )
            .bright_black()
        );

        println!(
            "{} {:016X}",
            "; VM Size     :".bright_black(),
            segment.vmsize
        );

        println!(
            "{} {:016X}",
            "; File Offset :".bright_black(),
            segment.fileoff
        );

        println!(
            "{} {:016X}",
            "; File Size   :".bright_black(),
            segment.filesize
        );

        println!("{}", ";".bright_black());

        if let Ok(sections) = segment.sections() {
            for (sec_idx, (section, _data)) in sections.into_iter().enumerate() {
                let name = section.name().unwrap_or("?");

                println!(
                    "{} {}",
                    ";".bright_black(),
                    format!(
                        "  Section {} '{}' (addr {:016X})",
                        sec_idx + 1,
                        name,
                        section.addr
                    )
                    .bright_black()
                );

                println!(
                    "{} {:016X}",
                    ";   Offset    :".bright_black(),
                    section.offset
                );

                println!("{} {:016X}", ";   Size      :".bright_black(), section.size);

                println!(
                    "{} {:08X}: {}",
                    ";   Flags     :".bright_black(),
                    section.flags,
                    format_macho_section_flags(Some(section.flags as u64)).bright_white()
                );

                println!("{}", ";".bright_black());
            }
        }
    }
}

// Header stile IDA Pro OLD

//pub fn print_ida_header(base_addr: u64, size: usize, section_name: &str) {
//    let separator = "─".repeat(60);
//    println!("{}", separator.bright_black());
//    println!(
//        "{}  {}",
//        "section:".bright_black(),
//        section_name.bright_yellow()
//    );
//    println!(
//        "{}  {:#018x}  {}  {:#x} bytes",
//        "range:".bright_black(),
//        base_addr,
//        "→".bright_black(),
//        size,
//    );
//    println!("{}", separator.bright_black());
//    println!();
//}
